# Dockerfile.dashboard

FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Install the new libraries
RUN pip install --no-cache-dir pika flask-socketio
COPY . .
# Run the dashboard app
CMD ["python", "dashboard_app.py"]